export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const  PRODUCT_SEARCH = 'PRODUCT_SEARCH'
export const  PRODUCT_CHANGE = 'PRODUCT_CHANGE'
export const ITEM_LOADING = 'ITEM_LOADING';
export const ITEM_SUCCESS = 'ITEM_SUCCESS';
